# Generated by Django 3.2.9 on 2021-11-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
